_target_: src.models.model.MainNet
lr: 1e-3
weight_decay: 0
net:
  _target_: src.models.components.base_transformer.BaseTransformer
  strand_out_dim: 256
  strand_kernel_size: 30
  concat_kernel_size: 30
  d_model: 64
  nhead: 8
  trfm_mlp_dim: 8
  trfm_layers: 2
  lstm_hidden_dim: 8
  mlp_hidden_dim: 64
  dropout: 0.05
  