_target_: src.models.model.MainNet
lr: 1e-3
weight_decay: 0
net:
  _target_: src.models.components.danq.DanQ_DS
  conv_out_dim: 160
  conv_kernel_size: 26
  pool_size: 3
  lstm_hidden_dim: 160
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  