_target_: src.models.model.MainNet
lr: 1e-3
weight_decay: 1e-5
net:
  _target_: src.models.components.danq.DanQ
  conv_out_dim: 320
  conv_kernel_size: 26
  pool_size: 13
  lstm_hidden_dim: 320
  fc_hidden_dim: 925
  dropout1: 0.2
  dropout2: 0.5
  