_target_: src.models.model.ConjoinedNet
lr: 1e-3
weight_decay: 0
net:
  _target_: src.models.components.danq_crc.DanQ_CRC
  conv_out_dim: 512
  conv_kernel_size: 10
  pool_size: 1
  lstm_hidden_dim: 320
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  