_target_: src.models.model.ConjoinedNet
lr: 1e-3
weight_decay: 1e-5
net:
  _target_: src.models.components.danq.DanQ_Transformer
  conv_out_dim: 320
  conv_kernel_size: 26
  pool_size: 3
  trfm_nhead: 8
  trfm_fc_dim: 320
  trfm_layers: 2
  fc_hidden_dim: 64
  dropout: 0.5
  