_target_: src.models.model.ConjoinedNet
lr: 0.0015
weight_decay: 0.025
net:
  _target_: src.models.components.deepfamq_crc.DeepFamQ_CRC
  conv_out_dim: 320
  conv_kernel_size: [9, 15]
  pool_size: 3
  lstm_hidden_dim: 320
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  