_target_: src.models.model.ConjoinedNet
lr: 1e-3
weight_decay: 0
net:
  _target_: src.models.components.deepfam.DeepFam
  conv_out_dim: 320
  conv_kernel_size: [10, 15]
  fc_hidden_dim: 256
  dropout: 0.5
  