_target_: src.models.model.ConjoinedNet_AW_CA
lr: 0.001
weight_decay: 0.01
max_epochs: 20
net:
  _target_: src.models.components.deepfamq.DeepFamQ
  conv_out_dim: 320
  conv_kernel_size: [10, 15]
  pool_size: 3
  lstm_hidden_dim: 320
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  