_target_: src.models.model.ConjoinedNet_AW_CAW
lr: 0.0001
weight_decay: 0.01
first_cycle_steps: 3
cycle_mult: 2.0
max_lr: 0.001
min_lr: 0.0001
warmup_steps: 2
gamma: 0.9
net:
  _target_: src.models.components.deepfamlight.DeepFamLight
  conv_out_dim: 320
  conv_kernel_size: [10, 15]
  pool_size: 3
  lstm_hidden_dim: 320
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  