_target_: src.models.distance.DistanceNet
lr: 1e-3
weight_decay: 0
lamb: 0.1
encoder:
  _target_: src.models.components.deepfamq_encoder.DeepFamQ_Encoder
  conv_out_dim: 320
  conv_kernel_size: [9, 15]
  pool_size: 3
  lstm_hidden_dim: 320
  embed_dim: 320
  dropout: 0.2
mlp:
  _target_: src.models.components.deepfamq_encoder.MLP
  input_dim: 320
  hidden_dim: 128
  n_layers: 3
  dropout: 0.5
  