_target_: src.models.model.ConjoinedNetCA
lr: 0.001
weight_decay: 0
first_cycle_steps: 500
cycle_mult: 1.5
min_lr: 0.0001
warmup_steps: 100
gamma: 0.9
net:
  _target_: src.models.components.deepgrn.DeepFamGRN
  conv_out_dim: 320
  conv_kernel_size: [10, 15]
  pool_size: 3
  lstm_hidden_dim: 160
  num_heads: 4
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  