_target_: src.models.model.ConjoinedNet
lr: 1e-3
weight_decay: 0
net:
  _target_: src.models.components.deepgrn.DeepFamGRN
  conv_out_dim: 320
  conv_kernel_size: [10, 15]
  pool_size: 3
  lstm_hidden_dim: 160
  num_heads: 4
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  