_target_: src.models.model.ConjoinedNet
lr: 0.0015
weight_decay: 0.025
net:
  _target_: src.models.components.deepfamq_crc_v2.DeepFamQ_CRC
  conv_out_dim: 512
  conv_kernel_sizes1: [9, 15]
  conv_kernel_sizes2: [7]
  pool_size: 1
  lstm_hidden_dim: 320
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5
  