_target_: src.models.reconstruct.ReconstructNet
lr: 1e-3
weight_decay: 0
lamb: 0.1
encoder:
  _target_: src.models.components.deepfamq_reconstruct_bilstm_conv.Encoder
  conv_out_dim: 320
  conv_kernel_size: [10, 15]
  lstm_hidden_dim: 320
  dropout1: 0.2
reconstructor:
  _target_: src.models.components.deepfamq_reconstruct_bilstm_conv.Reconstructor
  input_dim: 640
  hidden_dim: 160
  conv_kernel_size: 9
mlp:
  _target_: src.models.components.deepfamq_reconstruct_bilstm_conv.MLP
  hidden_dim: 64
  dropout: 0.5