_target_: src.models.model.MainNet
lr: 1e-3
weight_decay: 1e-5
net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  conv_out_dim: 256
  kernel_sizes: [8, 12, 16, 20, 24, 28, 32, 36]
  strand_out_dim: 256
  mlp_hidden_dim: 256
  