# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "dream-challenge"
  entity: "bhi-dream-challenge"
  name: ${name}_fold${fold}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  log_model: True
  prefix: ""
  job_type: "train"
  group: ${name}
  tags: []
