# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: default.yaml
  - model: base_transformer.yaml
  - callbacks: none.yaml
  - logger: none.yaml
  - trainer: default.yaml
  - log_dir: default.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

print_config: True

ignore_warnings: True

seed: 42

name: "default"

fold: 0

# passing checkpoint path is necessary
ckpt_path: logs/experiments/runs/${name}/fold${fold}/checkpoints/last.ckpt
