_target_: src.datamodules.datamodule_lrpadvec_lrtrim.MyDataModule

train_dir: ${oc.env:TRAIN_DATA} # specified in .env
test_dir: ${oc.env:TEST_DATA}
predict_dir: ${oc.env:PREDICT_DATA}
batch_size: 1024
num_workers: 4
fold: ${fold}
shift: False
one_hot: True
normalize: True
